# Generated by Django 3.0.7 on 2020-06-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20200610_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Jersey', 'Jersey'), ('Kit', 'Kit'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
